---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: buzzy-app
  namespace: buzzy
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: buzzy-app
    spec:
      # hostAliases: # Use this for testing when DNS is not yet set up
      #   - ip: IHS IP ADDRESS, e.g. "192.168.1.1"
      #     hostnames:
      #       - "minio.buzzy.net.au"
      #       - "logging.buzzy.net.au"
      #       - "buzzy.net.au"
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: buzzy-app-container
          image: docker.io/buzzybuzz/buzzy-main:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            # - name: NODE_TLS_REJECT_UNAUTHORIZED
            #   value: '0'
            - name: ROOT_URL
              value: "https://buzzy.net"
            - name: LOG_TO_STDOUT
              value: "1"
            - name: MONGO_URL
              value:  "mongodb://<username>:<password>@mongo-service:27017/buzzy?replicaSet=replicaset&authSource=admin"
            - name: MONGO_OPLOG_URL
              value: "mongodb://<username>:<password>@mongo-service:27017/local?replicaSet=replicaset&authSource=admin"
            - name: METEOR_SETTINGS
              value: '{
                "jwtSecret": "change-to-some-very-long-secret-string",
                "REPORT_ABUSE_EMAILS": ["someadminemail@emails.email"],
                "AWS_BUZZY_FILES": {
                  "enabled": true,
                  "accessKeyId": "ioueygr4t589",
                  "secretAccessKey": "7a863d41-2d8f-4143-bc8a-02501edbea6f",
                  "endpoint": "https://minio.buzzy.net.au"
                },
                "MAIL_URL": "smtp://someuser:somepassword@smtp.sendgrid.net:587",
                "BUZZY_ADMIN_EMAIL": "someadminemail",
                "DEFAULT_OAUTH_PROVIDERS": {
                  "enabled": true,
                  "defaultOrganizationName": "Organisation name",
                  "providers": [
                    {
                      "clientID": "someClientID",
                      "clientSecret": "someSecret",
                      "connectionsOrgID": "someConnectionsOrgID",
                      "name": "this will be your team name on login",
                      "signInDomain": "https://my.connections.com",
                      "type": "ibmconnectionsonprem"
                    }
                  ]
                },
                "BUZZY_ADMIN_IDS": ["adminuserid"],
                "BUZZY_LOGGING_TOKEN": "somelongtoken",
                "BUZZY_ADMIN_TOKEN": "somelongtoken",
                "BUZZY_CREATE_DEFAULT_ACCOUNTS": {
                  "enabled": true,
                  "accounts": [
                    {
                      "email": "someone@test.com",
                      "password": "somepassword",
                      "isAdmin": true
                    }
                  ]
                },
                "public": {
                  "BUZZY_DONOTREPLY_EMAIL": "donotreply2@buzzy.buzz",
                  "AWS_BUZZY_FILES": {
                    "enabled": true,
                    "S3FileExpiry": 604800,
                    "BUCKET_NAME": "buzzy-files",
                    "PUBLIC_BUCKET_NAME": "buzzy-files-public",
                    "s3ForcePathStyle": true,
                    "URL_PATTERN": "https://minio.buzzy.net.au/buzzy-files"
                  },
                  "IBMConnectionsOnPrem": {
                    "signInDomains": ["https://connections.example.net"],
                    "defaultClientID": "The same as the provider `name` in DEFAULT_OAUTH_PROVIDERS.providers.name above",
                  },
                  "IBMConnectionsCloud": {
                    "defaultClientID": "The same as the provider `name` in DEFAULT_OAUTH_PROVIDERS.providers.name above",
                    "defaultSignInDomain": "https://connections.example.net",
                    "alternateSignInDomains": []
                  },
                  "LOGINS": {
                    "SELF_REGISTRATION": {
                      "enabled": true
                    },
                    "IBM_CONNECTIONS_ONPREM": {
                      "enabled": true
                    }
                  },
                  "BUZZY_CUSTOM": {
                    "NAME": "Orgnisation Name",
                    "APP_URL_IOS": "",
                    "APP_URL_ANDROID": "",
                    "LOGO_MAIN": "",
                    "LOGO_MAIL": "",
                    "LOGO_MAIL_WIDTH": "60",
                    "LOGO_MAIL_HEIGHT": "25",
                    "EMAIL_FOOTER": "",
                    "PROMO": "",
                    "PROMO_URL": "",
                    "SPLASH_IMAGE": "",
                    "WELCOME_IMAGE": ""
                  },
                  "BUZZY_PROVIDERS": [
                    {
                      "name": "ibmconnectionscloud",
                      "displayName": "IBM Connections Cloud"
                    },
                    {
                      "name": "ibmconnectionsonprem",
                      "displayName": "IBM Connections On Premise"
                    }
                  ],
                  "BUZZY_LOGGING_SERVER": "https://logging.buzzy.net.au",
                  "BUZZY_TEMPLATE_SERVER": "https://a.buzzy.buzz",
                  "BUZZY_VERSION": "3.0.1"
                }
              }'
---

apiVersion: v1
kind: Service
metadata:
  name: buzzy-service
  namespace: buzzy
spec:
  type: NodePort
  selector:
    app: buzzy-app
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buzzy-ingress
  namespace: buzzy
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "200m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  # tls:
  #   - hosts:
  #       - buzzy.net.au
  #     secretName: buzzy-domain-secret
  rules:
     - host: buzzy.net.au
       http:
         paths:
           - backend:
              serviceName: buzzy-service
              servicePort: http
