---
#https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kudos-mongo
  labels:
    app: kudos-mongo
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv-kudos/mongo
    server: [STORAGE_SERVER_IP]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kudos-mongo-claim
  namespace: boards
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: "kudos-mongo"

---
kind: Deployment
# change this to "apiVersion: extensions/v1beta1" if running pre kube 1.16
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: boards
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: mongo
          image: bitnami/mongodb:4.4
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512M
          ports:
            - containerPort: 27017
          env:
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: mongo-service
          volumeMounts:
          - mountPath: /bitnami
            name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: kudos-mongo-claim

---
kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  namespace: boards
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
