# Please read every variable and replace with appropriate value
# For details of variable meanings, please see https://docs.huddo.com/boards/cp/

global:
  # setup authentication by following https://docs.huddo.com/boards/images/
  imagePullSecret: quay-username-pull-secret
  # find the latest release date https://docs.huddo.com/boards/releases/
  imageTag: 2024-08-29
  env:
    APP_URI: https://connections.example.com/boards
    API_GATEWAY: https://connections.example.com/api-boards

minio:
  # persistentVolumePath: pv-connections
  # useLegacyPodSecurityPolicy: true
  # useDockerHub: true
  nfs:
    server: 192.168.0.1

webfront:
  ingress:
    # This hostname must match other Ingresses defined in your CP environment
    # If all ingresses start with * you must match the pattern, or all traffic will be routed to Boards and everything will break
    # kubectl get ingresses --all-namespaces
    hosts:
      - "connections.example.com"
      # - "*.example.com"
  env:
    # DOCUMENTATION_URL: https://docs.huddo.com/boards/howto/knowledgebase/
    # PRODUCT_INFO_URL: https://huddo.com/boards
    # SUPPORT_EMAIL: support@example.com

events:
  env:
    NOTIFIER_EMAIL_HOST: smtp.example.com
    NOTIFIER_EMAIL_USERNAME: user123
    NOTIFIER_EMAIL_PASSWORD: passw0rd
    # APP_NAME: Huddo Boards # Used for all notifications, e.g. Orient Me
    # NOTIFIER_EMAIL_FROM_NAME: Huddo Boards
    # NOTIFIER_EMAIL_FROM_EMAIL: boards@connections.example.com

core:
  ingress:
    # This hostname must match other Ingresses defined in your CP environment
    # If all ingresses start with * you must match the pattern, or all traffic will be routed to Boards and everything will break
    # kubectl get ingresses --all-namespaces
    hosts:
      - "connections.example.com"
      # - "*.example.com"

licence:
  env:
    # Register your Organisation and download your Free 'Activities Plus' licence key from store.huddo.com
    LICENCE: secret-string-you-download

# https://docs.huddo.com/boards/msgraph/teams/on-prem/
# Uncomment/configure the following 3 lines if you are using this Huddo Boards deployment from Microsoft Teams
# provider:
#   env:
#     MSGRAPH_TEAMS_MANIFEST_ID: "<id attribute from your teams app manifest.json>"

user:
  env:
    # DISABLE_WELCOME_EMAIL: false
    # CONNECTIONS_NAME: HCL Connections
    # CONNECTIONS_CLIENT_ID: huddoboards
    CONNECTIONS_CLIENT_SECRET: long-secret-as-output-by-wsadmin-register
    CONNECTIONS_ADMINS: '["admin1@company.example.com", "boss2@company.example.com", "PROF_GUID_3"]'

migration:
  # configure access to the Connections Shared mount
  sharedDrive:
    # Replace with IP address for the NFS server
    server: 192.168.10.1
    # for example "/opt/HCL/Connections/data/shared" or "/nfs/data/shared"
    path: /nfs/data/shared
  env:
    # the extension after /data can be found from the WebSphere ACTIVITIES_CONTENT_DIR variable
    FILE_PATH_ACTIVITIES_CONTENT_STORE: /data/activities/content

    # Set the Timezone for this container, so dates are understood correctly
    # Please see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a full list of options
    # For example, uncomment one of the lines below (or add your own)
    # TZ: America/New_York
    # TZ: Australia/Hobart
    # TZ: Europe/London

    CONNECTIONS_ACTIVITIES_ADMIN_USERNAME: connectionsadmin
    CONNECTIONS_ACTIVITIES_ADMIN_PASSWORD: adminpassword
    CONNECTIONS_DB_HOST: dbserver.company.com
    CONNECTIONS_DB_USER: db2inst1
    CONNECTIONS_DB_PASSWORD: dbpassword

    # -------- DB2 variables ------------
    CONNECTIONS_DB_TYPE: db2
    CONNECTIONS_DB_PORT: 50000
    # Connection string is built from other variables:
    # CONNECTIONS_DB_CONNECT_STRING: HOSTNAME=${host};PORT=${port};PROTOCOL=TCPIP;UID=${user};PWD=${password};CHARSET=UTF8;

    # -------- Microsoft variables -------
    # CONNECTIONS_DB_TYPE: mssql
    # CONNECTIONS_DB_PORT: 1433
    # CONNECTIONS_DB_DOMAIN: domain

    # -------- Oracle variables ----------
    # CONNECTIONS_DB_TYPE: oracle
    # CONNECTIONS_DB_PORT: 1531
    # CONNECTIONS_DB_SID: DATABASE
    # Connection string is built from other variables:
    # CONNECTIONS_DB_CONNECT_STRING: ${host}:${port}/${sid}

    # -------- Other options -------------
    # PROCESSING_PAGE_SIZE: 10
    # PROCESSING_LOG_EVERY: 50
    # IMMEDIATELY_PROCESS_ALL: false
    # COMPLETE_ACTIVITY_AFTER_MIGRATED: false
    # CREATE_LINK_IN_ACTIVITY_AFTER_MIGRATED: false
